# Generated by Django 4.2.1 on 2023-05-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(default=20230000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='mail@host.com', max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('geneder', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('maritalStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1)),
                ('availableVacationDays', models.IntegerField(default=0)),
                ('approvedVacationDays', models.IntegerField(default=0)),
                ('salary', models.IntegerField(max_length=10)),
                ('birthDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('vacationReason', models.TextField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='HumanResources.employee')),
            ],
        ),
    ]
