# Generated by Django 4.2.1 on 2023-05-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_rename_vacations_vacation_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='HumanResources.employee'),
        ),
    ]
