# Generated by Django 4.2.1 on 2023-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_rename_employeeid_vacation_employee_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDay',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='geneder',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maritalStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
